export const styles = {
  container: {
    maxWidth: '1100px',
    margin: '0 auto',
    padding: '24px',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '32px',
    paddingBottom: '24px',
    borderBottom: '1px solid #1e3a5f',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  logo: { fontSize: '40px' },
  title: { fontSize: '24px', fontWeight: '700', color: '#e2e8f0' },
  subtitle: { fontSize: '13px', color: '#64748b', marginTop: '2px' },
  message: {
    padding: '12px 16px',
    borderRadius: '8px',
    border: '1px solid',
    marginBottom: '20px',
    fontSize: '14px',
  },
  card: {
    background: '#0d1526',
    border: '1px solid #1e3a5f',
    borderRadius: '12px',
    padding: '24px',
    marginBottom: '20px',
  },
  cardTitle: { fontSize: '16px', fontWeight: '600', color: '#93c5fd', marginBottom: '16px' },
  form: { display: 'flex', gap: '12px', flexWrap: 'wrap' },
  input: {
    background: '#0a0f1e',
    border: '1px solid #1e3a5f',
    borderRadius: '8px',
    padding: '10px 14px',
    color: '#e2e8f0',
    fontSize: '14px',
    flex: '1',
    minWidth: '180px',
    outline: 'none',
  },
  btnPrimary: {
    background: '#1d4ed8',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  tabs: { display: 'flex', gap: '8px', marginBottom: '16px' },
  tab: {
    background: 'transparent',
    border: '1px solid #1e3a5f',
    borderRadius: '8px',
    padding: '8px 20px',
    color: '#64748b',
    fontSize: '14px',
    cursor: 'pointer',
  },
  tabActive: { background: '#1e3a5f', color: '#93c5fd', borderColor: '#3b82f6' },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    textAlign: 'left',
    padding: '10px 12px',
    fontSize: '12px',
    color: '#64748b',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    borderBottom: '1px solid #1e3a5f',
  },
  tr: { borderBottom: '1px solid #0f1f3d' },
  td: { padding: '14px 12px', fontSize: '14px' },
  symbol: {
    background: '#1e3a5f',
    color: '#93c5fd',
    padding: '3px 8px',
    borderRadius: '4px',
    fontWeight: '700',
    fontSize: '13px',
  },
  rank: { color: '#64748b', fontWeight: '600' },
  btnRefresh: {
    background: '#1e3a5f',
    color: '#93c5fd',
    border: 'none',
    borderRadius: '6px',
    padding: '6px 12px',
    fontSize: '12px',
    cursor: 'pointer',
    marginRight: '8px',
  },
  btnDelete: {
    background: '#3b1a1a',
    color: '#ef4444',
    border: 'none',
    borderRadius: '6px',
    padding: '6px 12px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  empty: { color: '#64748b', fontSize: '14px', textAlign: 'center', padding: '40px' },
};