export const styles = {
  container: {
    maxWidth: '1100px',
    margin: '0 auto',
    padding: '24px',
    minHeight: '100vh',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '32px',
    paddingBottom: '24px',
    borderBottom: '1px solid #C4BEC8',
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  logo: { fontSize: '40px' },
  title: { fontSize: '24px', fontWeight: '700', color: '#000000' },
  subtitle: { fontSize: '13px', color: '#706D72', marginTop: '2px' },
  message: {
    padding: '12px 16px',
    borderRadius: '8px',
    border: '1px solid',
    marginBottom: '20px',
    fontSize: '14px',
  },
  card: {
    background: '#ffffff',
    border: '1px solid #C4BEC8',
    borderRadius: '12px',
    padding: '24px',
    marginBottom: '20px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },
  cardTitle: { fontSize: '16px', fontWeight: '600', color: '#000000', marginBottom: '16px' },
  form: { display: 'flex', gap: '12px', flexWrap: 'wrap' },
  input: {
    background: '#DFD9E4',
    border: '1px solid #C4BEC8',
    borderRadius: '8px',
    padding: '10px 14px',
    color: '#000000',
    fontSize: '14px',
    flex: '1',
    minWidth: '180px',
    outline: 'none',
  },
  btnPrimary: {
    background: '#000000',
    color: '#DFD9E4',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  tabs: { display: 'flex', gap: '8px', marginBottom: '16px' },
  tab: {
    background: 'transparent',
    border: '1px solid #C4BEC8',
    borderRadius: '8px',
    padding: '8px 20px',
    color: '#706D72',
    fontSize: '14px',
    cursor: 'pointer',
  },
  tabActive: {
    background: '#000000',
    color: '#DFD9E4',
    borderColor: '#000000',
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    textAlign: 'left',
    padding: '10px 12px',
    fontSize: '12px',
    color: '#706D72',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    borderBottom: '1px solid #C4BEC8',
  },
  tr: { borderBottom: '1px solid #DFD9E4' },
  td: { padding: '14px 12px', fontSize: '14px', color: '#000000' },
  symbol: {
    background: '#000000',
    color: '#DFD9E4',
    padding: '3px 8px',
    borderRadius: '4px',
    fontWeight: '700',
    fontSize: '13px',
  },
  rank: { color: '#706D72', fontWeight: '600' },
  btnRefresh: {
    background: '#DFD9E4',
    color: '#000000',
    border: '1px solid #C4BEC8',
    borderRadius: '6px',
    padding: '6px 12px',
    fontSize: '12px',
    cursor: 'pointer',
    marginRight: '8px',
  },
  btnDelete: {
    background: '#000000',
    color: '#DFD9E4',
    border: 'none',
    borderRadius: '6px',
    padding: '6px 12px',
    fontSize: '12px',
    cursor: 'pointer',
  },
  empty: { color: '#A8A3AB', fontSize: '14px', textAlign: 'center', padding: '40px' },

  // Popup styles
  overlay: {
    position: 'fixed',
    top: 0, left: 0, right: 0, bottom: 0,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  popup: {
    background: '#ffffff',
    border: '1px solid #C4BEC8',
    borderRadius: '16px',
    padding: '32px',
    maxWidth: '400px',
    width: '90%',
    boxShadow: '0 8px 32px rgba(0,0,0,0.12)',
    textAlign: 'center',
  },
  popupIcon: { fontSize: '40px', marginBottom: '16px' },
  popupTitle: { fontSize: '18px', fontWeight: '700', color: '#000000', marginBottom: '8px' },
  popupText: { fontSize: '14px', color: '#706D72', marginBottom: '24px' },
  popupActions: { display: 'flex', gap: '12px', justifyContent: 'center' },
  btnCancel: {
    background: '#DFD9E4',
    color: '#000000',
    border: '1px solid #C4BEC8',
    borderRadius: '8px',
    padding: '10px 24px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  btnConfirm: {
    background: '#000000',
    color: '#DFD9E4',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 24px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
  },
};